name: connect_to_server
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  validators: ^3.0.0
  http: ^0.13.5
  dio: ^5.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  # generate: true
  uses-material-design: true
